package com.micatechnologies.realgrid.blocks.bankmounts;

import com.micatechnologies.realgrid.RealGrid;
import com.micatechnologies.realgrid.blocks.insulators.BlockInsulatorBase;
import com.micatechnologies.realgrid.init.RealGridRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.block.properties.PropertyDirection;
import net.minecraft.block.state.BlockStateContainer;
import net.minecraft.block.state.IBlockState;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.util.BlockRenderLayer;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.EnumHand;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

/**
 * Steel box frame that carries a bank of pole-mounted transformers, LADWP / SCE style.
 * Decorative: no wires, no tile entity.
 *
 * <p>The frame fills the block in front of the pole, two blocks tall like the transformers, and is
 * bolted to the pole behind it; the back of the pole is left for bolt covers. {@link #FACING} points
 * away from the pole. Transformers stand flush against the frame the way they stand flush against
 * a log, their back lugs at the edge of its block:
 *
 * <ul>
 *   <li>Three-transformer bank: one tank on each side of the frame, facing outwards, and one on its
 *       front. LADWP frames brace their sides with an X, SCE frames with straight arms.</li>
 *   <li>Two-transformer bank: a smaller frame with one tank on each side.</li>
 * </ul>
 *
 * <p>The frame fills its block, so clicking one of its faces places a transformer against that face.
 * The models are placeholders generated by scripts/gen_transformer_bank_mounts.py.
 */
public class BlockTransformerBankMount extends Block
{
    public static final PropertyDirection FACING = PropertyDirection.create("facing", EnumFacing.Plane.HORIZONTAL);

    private final int transformers;

    /**
     * @param style        the frame's style as it appears in the registry name ("ladwp", "sce"), or
     *                     null for the one two-transformer frame
     * @param transformers how many transformers the frame carries
     */
    public BlockTransformerBankMount(String style, int transformers)
    {
        super(Material.IRON);
        this.transformers = transformers;
        String registryName = "transformer_bank_mount_" + (style == null ? "" : style + "_") + transformers;
        setRegistryName(RealGrid.MODID, registryName);
        setTranslationKey(RealGrid.MODID + "." + registryName);
        setHardness(2.0f);
        setResistance(10.0f);
        setDefaultState(blockState.getBaseState().withProperty(FACING, EnumFacing.NORTH));
        RealGridRegistry.registerBlock(this);
    }

    /** @return how many transformers the bank this frame carries has */
    public int getTransformers()
    {
        return transformers;
    }

    @Override
    protected BlockStateContainer createBlockState()
    {
        return new BlockStateContainer(this, FACING);
    }

    @Override
    public IBlockState getStateFromMeta(int meta)
    {
        return getDefaultState().withProperty(FACING, EnumFacing.byHorizontalIndex(meta & 3));
    }

    @Override
    public int getMetaFromState(IBlockState state)
    {
        return state.getValue(FACING).getHorizontalIndex();
    }

    /**
     * Clicking the front of the pole stands the frame off that face. A top or bottom face has no
     * side to go on, so the frame faces the player.
     */
    @Override
    public IBlockState getStateForPlacement(World world, BlockPos pos, EnumFacing side,
                                            float hitX, float hitY, float hitZ,
                                            int meta, EntityLivingBase placer, EnumHand hand)
    {
        EnumFacing facing = side.getAxis().isHorizontal() ? side : placer.getHorizontalFacing().getOpposite();
        return getDefaultState().withProperty(FACING, facing);
    }

    /** Drops the frame once nothing holds it up, by the same rule as the insulators. */
    @Override
    public void neighborChanged(IBlockState state, World world, BlockPos pos, Block block, BlockPos fromPos)
    {
        super.neighborChanged(state, world, pos, block, fromPos);
        if (world.isRemote || BlockInsulatorBase.hasAnySupport(world, pos))
            return;
        dropBlockAsItem(world, pos, state, 0);
        world.setBlockToAir(pos);
    }

    @Override
    public BlockRenderLayer getRenderLayer()
    {
        return BlockRenderLayer.CUTOUT;
    }

    @Override
    public boolean isOpaqueCube(IBlockState state) { return false; }

    @Override
    public boolean isFullCube(IBlockState state) { return false; }
}
