package com.micatechnologies.realgrid.blocks.bankmounts;

import com.micatechnologies.realgrid.RealGrid;
import com.micatechnologies.realgrid.blocks.insulators.BlockInsulatorBase;
import com.micatechnologies.realgrid.init.RealGridRegistry;
import com.micatechnologies.realgrid.util.BoundsUtil;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.block.properties.PropertyDirection;
import net.minecraft.block.properties.PropertyEnum;
import net.minecraft.block.state.BlockStateContainer;
import net.minecraft.block.state.IBlockState;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.util.BlockRenderLayer;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.EnumHand;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.RayTraceResult;
import net.minecraft.util.text.TextComponentTranslation;
import net.minecraft.world.IBlockAccess;
import net.minecraft.world.World;

import java.util.Random;

/**
 * Steel frame that carries a bank of pole-mounted transformers, LADWP / SCE style.
 * Decorative: no wires, no tile entity.
 *
 * <p>The frame stands in front of the pole, drawn two blocks tall like the transformers, and is
 * bolted to the pole behind it; the back of the pole is left for bolt covers. {@link #FACING} points
 * away from the pole. Transformers stand flush against the frame the way they stand flush against
 * a log, their back lugs at the edge of its block:
 *
 * <ul>
 *   <li>Three-transformer bank: three blocks in a row ({@link #PART}). The centre, bolted to the
 *       pole, carries the front tank on its front face; an arm either side carries a side tank on
 *       its outer face, facing outwards. LADWP arms taper from a tall post at the side tank to a
 *       small cage at the centre, so the pair reads as an X; SCE arms are straight. The centre's box
 *       is the whole block; the arms' boxes are slim and low, clear of the tanks' wires. Placing the
 *       centre puts out both arms, and breaking any part takes down the whole frame.</li>
 *   <li>Two-transformer bank: an H-shaped bracket standing off the pole, one tank on each side.</li>
 * </ul>
 *
 * <p>The models are generated by scripts/gen_transformer_bank_mounts.py.
 */
public class BlockTransformerBankMount extends Block
{
    public static final PropertyDirection FACING = PropertyDirection.create("facing", EnumFacing.Plane.HORIZONTAL);
    public static final PropertyEnum<BankMountPart> PART = PropertyEnum.create("part", BankMountPart.class);

    /**
     * The two-transformer bracket, for a north-facing mount: from the tanks' centre line back to the
     * pole, and only as high as the lower cross bar and its lug clamps, so the box stays clear of
     * the tanks' bushings and the wires leaving them.
     */
    private static final float[] BRACKET_BOUNDS = {0.0f, 0.0f, 0.3125f, 1.0f, 0.625f, 1.0f};

    /**
     * A three-transformer bank's arm: slim and low, round the lower member at the tanks' lug depth,
     * reaching both ends of its block so a side tank can be put against the outer face.
     */
    private static final AxisAlignedBB ARM_BOUNDS = new AxisAlignedBB(0.0, 0.0, 0.25, 1.0, 0.45, 0.75);

    private final int transformers;

    /**
     * @param style        the frame's style as it appears in the registry name ("ladwp", "sce"), or
     *                     null for the one two-transformer frame
     * @param transformers how many transformers the frame carries
     */
    public BlockTransformerBankMount(String style, int transformers)
    {
        super(Material.IRON);
        this.transformers = transformers;
        String registryName = "transformer_bank_mount_" + (style == null ? "" : style + "_") + transformers;
        setRegistryName(RealGrid.MODID, registryName);
        setTranslationKey(RealGrid.MODID + "." + registryName);
        setHardness(2.0f);
        setResistance(10.0f);
        setDefaultState(blockState.getBaseState().withProperty(FACING, EnumFacing.NORTH).withProperty(PART, BankMountPart.CENTER));
        RealGridRegistry.registerBlock(this);
    }

    /** @return how many transformers the bank this frame carries has */
    public int getTransformers()
    {
        return transformers;
    }

    private boolean hasArms()
    {
        return transformers == 3;
    }

    @Override
    protected BlockStateContainer createBlockState()
    {
        return new BlockStateContainer(this, FACING, PART);
    }

    /** Bits 0-1: facing. Bits 2-3: part. Frames from before the arms existed read as a lone centre. */
    @Override
    public IBlockState getStateFromMeta(int meta)
    {
        return getDefaultState()
            .withProperty(FACING, EnumFacing.byHorizontalIndex(meta & 3))
            .withProperty(PART, BankMountPart.byIndex((meta >> 2) & 3));
    }

    @Override
    public int getMetaFromState(IBlockState state)
    {
        return state.getValue(FACING).getHorizontalIndex() | (state.getValue(PART).ordinal() << 2);
    }

    // -----------------------------------------------------------------------
    // Placement
    // -----------------------------------------------------------------------

    /**
     * Clicking the front of the pole stands the frame off that face. A top or bottom face has no
     * side to go on, so the frame faces the player.
     */
    @Override
    public IBlockState getStateForPlacement(World world, BlockPos pos, EnumFacing side,
                                            float hitX, float hitY, float hitZ,
                                            int meta, EntityLivingBase placer, EnumHand hand)
    {
        EnumFacing facing = side.getAxis().isHorizontal() ? side : placer.getHorizontalFacing().getOpposite();
        return getDefaultState().withProperty(FACING, facing);
    }

    /**
     * A three-transformer frame puts out its arms either side. With no room for both, the
     * placement is undone and the frame handed back.
     */
    @Override
    public void onBlockPlacedBy(World world, BlockPos pos, IBlockState state, EntityLivingBase placer, ItemStack stack)
    {
        if (world.isRemote || !hasArms())
            return;
        EnumFacing facing = state.getValue(FACING);
        BlockPos left = pos.offset(BankMountPart.LEFT.sideOf(facing));
        BlockPos right = pos.offset(BankMountPart.RIGHT.sideOf(facing));
        if (world.getBlockState(left).getBlock().isReplaceable(world, left)
            && world.getBlockState(right).getBlock().isReplaceable(world, right))
        {
            world.setBlockState(left, state.withProperty(PART, BankMountPart.LEFT), 3);
            world.setBlockState(right, state.withProperty(PART, BankMountPart.RIGHT), 3);
            return;
        }
        world.setBlockToAir(pos);
        if (placer instanceof EntityPlayer)
        {
            EntityPlayer player = (EntityPlayer) placer;
            player.sendStatusMessage(new TextComponentTranslation("realgrid.transformer_bank_mount.arms_blocked"), true);
            if (!player.capabilities.isCreativeMode)
                player.inventory.addItemStackToInventory(new ItemStack(this));
        }
    }

    // -----------------------------------------------------------------------
    // Parts
    // -----------------------------------------------------------------------

    /** @return the centre of the frame this part belongs to */
    private static BlockPos centreOf(IBlockState state, BlockPos pos)
    {
        EnumFacing toPart = state.getValue(PART).sideOf(state.getValue(FACING));
        return toPart == null ? pos : pos.offset(toPart.getOpposite());
    }

    /** @return whether {@code centre} holds the centre the arm in state {@code arm} belongs to */
    private boolean isCentreFor(IBlockAccess world, BlockPos centre, IBlockState arm)
    {
        IBlockState c = world.getBlockState(centre);
        return c.getBlock() == this && c.getValue(PART) == BankMountPart.CENTER
            && c.getValue(FACING) == arm.getValue(FACING);
    }

    /**
     * The centre drops once nothing holds it up, by the same rule as the insulators; an arm goes as
     * soon as its centre does.
     */
    @Override
    public void neighborChanged(IBlockState state, World world, BlockPos pos, Block block, BlockPos fromPos)
    {
        super.neighborChanged(state, world, pos, block, fromPos);
        if (world.isRemote)
            return;
        if (state.getValue(PART) != BankMountPart.CENTER)
        {
            if (!isCentreFor(world, centreOf(state, pos), state))
                world.setBlockToAir(pos);
            return;
        }
        if (BlockInsulatorBase.hasAnySupport(world, pos))
            return;
        dropBlockAsItem(world, pos, state, 0);
        world.setBlockToAir(pos);
    }

    /**
     * Breaking the centre takes its arms with it. Breaking an arm breaks the centre, which drops the
     * frame; the arm's position is air by then, so the centre clearing its arms leaves it alone.
     */
    @Override
    public void breakBlock(World world, BlockPos pos, IBlockState state)
    {
        if (!world.isRemote && hasArms())
        {
            EnumFacing facing = state.getValue(FACING);
            if (state.getValue(PART) == BankMountPart.CENTER)
            {
                for (BankMountPart arm : new BankMountPart[]{BankMountPart.LEFT, BankMountPart.RIGHT})
                {
                    BlockPos at = pos.offset(arm.sideOf(facing));
                    IBlockState there = world.getBlockState(at);
                    if (there.getBlock() == this && there.getValue(PART) == arm && there.getValue(FACING) == facing)
                        world.setBlockToAir(at);
                }
            }
            else
            {
                BlockPos centre = centreOf(state, pos);
                if (isCentreFor(world, centre, state))
                    world.destroyBlock(centre, true);
            }
        }
        super.breakBlock(world, pos, state);
    }

    /** A creative player breaking an arm takes the frame down without dropping it. */
    @Override
    public boolean removedByPlayer(IBlockState state, World world, BlockPos pos, EntityPlayer player, boolean willHarvest)
    {
        if (!world.isRemote && player.capabilities.isCreativeMode && state.getValue(PART) != BankMountPart.CENTER)
        {
            BlockPos centre = centreOf(state, pos);
            if (isCentreFor(world, centre, state))
                world.setBlockToAir(centre);
        }
        return super.removedByPlayer(state, world, pos, player, willHarvest);
    }

    /** Only the centre drops the frame. */
    @Override
    public Item getItemDropped(IBlockState state, Random rand, int fortune)
    {
        return state.getValue(PART) == BankMountPart.CENTER ? super.getItemDropped(state, rand, fortune) : Items.AIR;
    }

    @Override
    public int damageDropped(IBlockState state)
    {
        return 0;
    }

    @Override
    public ItemStack getPickBlock(IBlockState state, RayTraceResult target, World world, BlockPos pos, EntityPlayer player)
    {
        return new ItemStack(this);
    }

    // -----------------------------------------------------------------------
    // Shape and rendering
    // -----------------------------------------------------------------------

    @Override
    public AxisAlignedBB getBoundingBox(IBlockState state, IBlockAccess source, BlockPos pos)
    {
        if (transformers == 2)
        {
            float[] b = BoundsUtil.rotateBounds(BRACKET_BOUNDS, state.getValue(FACING));
            return new AxisAlignedBB(b[0], b[1], b[2], b[3], b[4], b[5]);
        }
        if (state.getValue(PART) == BankMountPart.CENTER)
            return FULL_BLOCK_AABB;
        float[] north = {(float) ARM_BOUNDS.minX, (float) ARM_BOUNDS.minY, (float) ARM_BOUNDS.minZ,
                         (float) ARM_BOUNDS.maxX, (float) ARM_BOUNDS.maxY, (float) ARM_BOUNDS.maxZ};
        float[] b = BoundsUtil.rotateBounds(north, state.getValue(FACING));
        return new AxisAlignedBB(b[0], b[1], b[2], b[3], b[4], b[5]);
    }

    @Override
    public BlockRenderLayer getRenderLayer()
    {
        return BlockRenderLayer.CUTOUT;
    }

    @Override
    public boolean isOpaqueCube(IBlockState state) { return false; }

    @Override
    public boolean isFullCube(IBlockState state) { return false; }
}
