package com.micatechnologies.realgrid.blocks.bankmounts;

import com.micatechnologies.realgrid.RealGrid;
import com.micatechnologies.realgrid.blocks.insulators.BlockInsulatorBase;
import com.micatechnologies.realgrid.init.RealGridRegistry;
import com.micatechnologies.realgrid.util.BoundsUtil;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.block.properties.PropertyDirection;
import net.minecraft.block.state.BlockStateContainer;
import net.minecraft.block.state.IBlockState;
import net.minecraft.entity.EntityLivingBase;
import net.minecraft.util.BlockRenderLayer;
import net.minecraft.util.EnumFacing;
import net.minecraft.util.EnumHand;
import net.minecraft.util.math.AxisAlignedBB;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.IBlockAccess;
import net.minecraft.world.World;

/**
 * Steel channel frame that carries a bank of pole-mounted transformers, LADWP / SCE style.
 * Decorative: no wires, no tile entity.
 *
 * <p>Transformers stand flush against a log pole, so the frame cannot go between tank and pole. It
 * hangs on one face of the pole instead, on the same level as the transformers' lower half, and its
 * channels run across that face at the tanks' lug heights, overhanging the blocks either side and
 * the block above. {@link #FACING} points away from the pole.
 *
 * <ul>
 *   <li>Three-transformer bank: tanks on the pole's other three faces; the channels wrap onto the
 *       two side tanks.</li>
 *   <li>Two-transformer bank: two tanks side by side, left and right of the mount, facing away from
 *       the pole with their backs on the channels.</li>
 * </ul>
 *
 * <p>The models are placeholders generated by scripts/gen_transformer_bank_mounts.py.
 */
public class BlockTransformerBankMount extends Block
{
    public static final PropertyDirection FACING = PropertyDirection.create("facing", EnumFacing.Plane.HORIZONTAL);

    /** The pole strap and the part of the channels inside this block, for a north-facing mount. */
    private static final float[] NORTH_BOUNDS = {0.0f, 0.0f, 0.875f, 1.0f, 1.0f, 1.0f};

    private final int transformers;

    public BlockTransformerBankMount(int transformers)
    {
        super(Material.IRON);
        this.transformers = transformers;
        String registryName = "transformer_bank_mount_" + transformers;
        setRegistryName(RealGrid.MODID, registryName);
        setTranslationKey(RealGrid.MODID + "." + registryName);
        setHardness(2.0f);
        setResistance(10.0f);
        setDefaultState(blockState.getBaseState().withProperty(FACING, EnumFacing.NORTH));
        RealGridRegistry.registerBlock(this);
    }

    /** @return how many transformers the bank this frame carries has */
    public int getTransformers()
    {
        return transformers;
    }

    @Override
    protected BlockStateContainer createBlockState()
    {
        return new BlockStateContainer(this, FACING);
    }

    @Override
    public IBlockState getStateFromMeta(int meta)
    {
        return getDefaultState().withProperty(FACING, EnumFacing.byHorizontalIndex(meta & 3));
    }

    @Override
    public int getMetaFromState(IBlockState state)
    {
        return state.getValue(FACING).getHorizontalIndex();
    }

    /**
     * Clicking a side of the pole hangs the frame on that side. A top or bottom face has no side to
     * go on, so the frame faces the player.
     */
    @Override
    public IBlockState getStateForPlacement(World world, BlockPos pos, EnumFacing side,
                                            float hitX, float hitY, float hitZ,
                                            int meta, EntityLivingBase placer, EnumHand hand)
    {
        EnumFacing facing = side.getAxis().isHorizontal() ? side : placer.getHorizontalFacing().getOpposite();
        return getDefaultState().withProperty(FACING, facing);
    }

    /** Drops the frame once nothing holds it up, by the same rule as the insulators. */
    @Override
    public void neighborChanged(IBlockState state, World world, BlockPos pos, Block block, BlockPos fromPos)
    {
        super.neighborChanged(state, world, pos, block, fromPos);
        if (world.isRemote || BlockInsulatorBase.hasAnySupport(world, pos))
            return;
        dropBlockAsItem(world, pos, state, 0);
        world.setBlockToAir(pos);
    }

    @Override
    public AxisAlignedBB getBoundingBox(IBlockState state, IBlockAccess source, BlockPos pos)
    {
        float[] b = BoundsUtil.rotateBounds(NORTH_BOUNDS, state.getValue(FACING));
        return new AxisAlignedBB(b[0], b[1], b[2], b[3], b[4], b[5]);
    }

    @Override
    public BlockRenderLayer getRenderLayer()
    {
        return BlockRenderLayer.CUTOUT;
    }

    @Override
    public boolean isOpaqueCube(IBlockState state) { return false; }

    @Override
    public boolean isFullCube(IBlockState state) { return false; }
}
