#!/usr/bin/env python3
"""Generates the models, blockstates and placeholder textures for the crossarms (issue #38).

Run from the repository root:

    python scripts/gen_crossarms.py

A crossarm is built from one-block segments that join into an arm of any length (BlockCrossarm).
A segment is drawn from parts, put together by a multipart blockstate from its state: the beam,
its ends where the arm carries on (left / right), the through-bolt where it sits against a pole
(pole), and the hardware for what is mounted on it, which appears by itself: an insulator pin's nut
under the arm (pin), a hanger strap down to an IE connector below it (hanger), and an eyebolt on
each face something hangs from (front_fit, back_fit, left_fit, right_fit). The parts are plain JSON
models, so materials only change the beam's texture. The Java side relies on the file names, the
property names, and on the arm's cross-section matching BlockCrossarm.ARM_BOUNDS.

Coordinate system (as in gen_pole_light_mounts.py): one unit is one block, the segment's block spans
0..1, the segment faces NORTH (away from the pole) and the pole is the block to its SOUTH (z 1..2).
The arm runs along x. Left and right are seen looking out from the pole, so left is west (-x).
The blockstate rotates the models to the other facings.

V-braces (BlockCrossarmBrace) go one block below the arm, in front of the pole. A brace's point is
bolted to the pole's face; each leg runs up to the arm's front face one block out to that side, and
is drawn only while the arm carries on that far (left / right in its blockstate). Their models use
the same coordinates, with the arm in the block above (y 1..2).
"""

import json
import os

from gen_pole_light_mounts import Obj, png, write

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'main', 'resources', 'assets', 'realgrid')
MODEL_DIR = os.path.join(ROOT, 'models', 'block', 'crossarm')
BLOCKSTATE_DIR = os.path.join(ROOT, 'blockstates')
TEXTURE_DIR = os.path.join(ROOT, 'textures', 'blocks')
ITEM_MODEL_DIR = os.path.join(ROOT, 'models', 'item')

HEADER = '# Generated by scripts/gen_crossarms.py\n'
PX = 1 / 16
FACINGS = (('north', 0), ('east', 90), ('south', 180), ('west', 270))

ARM_LO = 10 * PX          # the arm's cross-section: 6 px square at the top back of the block
END_INSET = 0.5 * PX      # an open end stops just short of its block's edge

# name: (base colour, grain spread) of the placeholder wood texture
MATERIALS = {
    'brooks_brown': ((122, 84, 56), 10),
}

# V-braces: kind -> (texture, strap half-thickness)
BRACES = {
    'wood': ('realgrid:blocks/crossarm_brace_wood', 1.2 * PX),
    'metal': ('realgrid:blocks/pole_light_mount_metal', 0.8 * PX),
}
BRACE_POINT = (0.5, 0.55, 15.2 * PX)     # where the point is bolted to the pole's face
BRACE_REACH = 1.0                        # how far out either side the legs meet the arm
BRACE_TOP = 1.0 + ARM_LO + 1.5 * PX      # where a leg meets the arm's front face, in the block above
BRACE_FRONT = ARM_LO - 0.4 * PX          # just in front of the arm's front face


ARM_MID_Z = (ARM_LO + 1.0) / 2       # the arm's centre line, where a seated insulator's pin goes through


def brace_model(kind, left, right):
    _, half = BRACES[kind]
    obj = Obj('crossarm_brace_%s_%s' % (kind, key(left, right, False)), 'brace.mtl', HEADER)
    px, py, pz = BRACE_POINT
    obj.use('clamp')
    obj.box((px - 2.5 * PX, py - 1.5 * PX, 15.4 * PX), (px + 2.5 * PX, py + 2.5 * PX, 1.0))          # plate on the pole
    for on, sign in ((left, -1), (right, 1)):
        if not on:
            continue
        end = (px + sign * BRACE_REACH, BRACE_TOP, BRACE_FRONT)
        obj.use('strap')
        obj.tube([(px + sign * 1.5 * PX, py + 0.5 * PX, pz), end], half, sides=4)
        obj.use('clamp')
        obj.box((end[0] - 1 * PX, end[1] - 1 * PX, end[2] - 1 * PX), (end[0] + 1 * PX, end[1] + 1 * PX, ARM_LO))   # bolt into the arm
    return obj.text()


def brace_mtl(kind):
    texture, _ = BRACES[kind]
    return HEADER + 'newmtl strap\nmap_Kd %s\nnewmtl clamp\nmap_Kd realgrid:blocks/pole_light_mount_clamp\n' % texture


def brace_blockstate(kind):
    variants = {}
    for facing, y in FACINGS:
        for left in (False, True):
            for right in (False, True):
                variants['facing=%s,left=%s,right=%s' % (facing, str(left).lower(), str(right).lower())] = {
                    'model': 'realgrid:crossarm/brace_%s/brace_%s.obj' % (kind, key(left, right, False)),
                    'custom': {'flip-v': True}, 'y': y}
    variants['inventory'] = {
        'model': 'realgrid:crossarm/brace_%s/brace_%s.obj' % (kind, key(True, True, False)),
        'custom': {'flip-v': True},
        'transform': {
            'gui': {'translation': [0, -0.15, 0], 'rotation': [{'x': 30}, {'y': 135}], 'scale': 0.45},
            'ground': {'translation': [0, 0.1, 0], 'scale': 0.3},
            'fixed': {'rotation': [{'y': 180}], 'scale': 0.45},
            'thirdperson': {'translation': [0, 0.1, 0.1], 'rotation': [{'x': 75}, {'y': 45}], 'scale': 0.35},
            'firstperson': {'translation': [0.1, 0.1, 0], 'rotation': [{'y': 45}], 'scale': 0.35},
        },
    }
    return {'forge_marker': 1, 'variants': variants}


def key(left, right, pole, pin=False, hanger=False):
    """'lrpih'-style suffix: which of left, right, pole, pin and hanger are set."""
    return ''.join(c for c, on in (('l', left), ('r', right), ('p', pole), ('i', pin), ('h', hanger)) if on) or 'none'


BOOLS = (False, True)



# ---------------------------------------------------------------------------------------------
# Crossarm segments: JSON parts and a multipart blockstate
# ---------------------------------------------------------------------------------------------

STEEL = 'realgrid:blocks/pole_light_mount_clamp'

# part name: (texture variable, [(from, to) boxes in pixels, north-facing]), and the condition it
# shows on. Boxes are in the segment's own block; the arm is 10-16 px up and 10-16 px deep.
ARM_PARTS = {
    'beam': ('wood', [((0.5, 10, 10), (15.5, 16, 16))]),
    'beam_left': ('wood', [((0, 10, 10), (0.5, 16, 16))]),
    'beam_right': ('wood', [((15.5, 10, 10), (16, 16, 16))]),
    # Through-bolt at the pole: square washer and nut on the arm's front face.
    'pole_bolt': ('steel', [((6, 11, 9.6), (10, 15, 10)), ((7, 12, 9), (9, 14, 9.6))]),
    # An insulator pin's washer and nut, under the arm on its centre line.
    'pin': ('steel', [((6.5, 9.6, 11.5), (9.5, 10, 14.5)), ((7.25, 8.6, 12.25), (8.75, 9.6, 13.75))]),
    # A strap down from the arm and a plate at the bottom of the block, over a connector hung there.
    'hanger': ('steel', [((7, 1.5, 12), (9, 10, 14)), ((7, 0, 6), (9, 1.5, 14)), ((5, 0, 5), (11, 0.75, 11))]),
    # Eyebolts for what hangs off each face.
    'front_fit': ('steel', [((6.5, 11.5, 9.6), (9.5, 14.5, 10)), ((7.5, 12.25, 8.4), (8.5, 13.75, 9.6))]),
    'back_fit': ('steel', [((6.5, 11.5, 16), (9.5, 14.5, 16.4)), ((7.5, 12.25, 16.4), (8.5, 13.75, 17.6))]),
    'left_fit': ('steel', [((-0.4, 11.5, 11.5), (0, 14.5, 14.5)), ((-1.6, 12.25, 12.5), (-0.4, 13.75, 13.5))]),
    'right_fit': ('steel', [((16, 11.5, 11.5), (16.4, 14.5, 14.5)), ((16.4, 12.25, 12.5), (17.6, 13.75, 13.5))]),
}
PART_WHEN = {
    'beam': {},
    'beam_left': {'left': 'true'},
    'beam_right': {'right': 'true'},
    'pole_bolt': {'pole': 'true', 'front_fit': 'false'},     # an eyebolt takes the through-bolt's place
    'pin': {'pin': 'true'},
    'hanger': {'hanger': 'true'},
    'front_fit': {'front_fit': 'true'},
    'back_fit': {'back_fit': 'true'},
    'left_fit': {'left_fit': 'true'},
    'right_fit': {'right_fit': 'true'},
}


def json_model(texture_var, boxes, textures=None):
    elements = []
    for lo, hi in boxes:
        faces = {f: {'texture': '#' + texture_var} for f in ('north', 'south', 'east', 'west', 'up', 'down')}
        elements.append({'from': list(lo), 'to': list(hi), 'faces': faces})
    model = {'__comment': 'Generated by scripts/gen_crossarms.py', 'elements': elements}
    if textures:
        model['textures'] = textures
    return model


def part_model(material, part):
    var, boxes = ARM_PARTS[part]
    tex = 'realgrid:blocks/crossarm_%s' % material if var == 'wood' else STEEL
    return json_model(var, boxes, {var: tex, 'particle': 'realgrid:blocks/crossarm_%s' % material})


def multipart(material):
    parts = []
    for facing, y in FACINGS:
        for part, when in PART_WHEN.items():
            cond = dict(when, facing=facing)
            parts.append({'when': cond, 'apply': {'model': 'realgrid:crossarm/%s/%s' % (material, part), 'y': y}})
    return {'multipart': parts}


def item_model(material):
    """The item: one segment with both ends carried on and the pole bolt, from the parts."""
    wood = ARM_PARTS['beam_left'][1] + ARM_PARTS['beam'][1] + ARM_PARTS['beam_right'][1]
    model = json_model('wood', wood, {'wood': 'realgrid:blocks/crossarm_%s' % material, 'steel': STEEL,
                                      'particle': 'realgrid:blocks/crossarm_%s' % material})
    model['elements'] += json_model('steel', ARM_PARTS['pole_bolt'][1])['elements']
    model['display'] = {
        'gui': {'rotation': [30, 225, 0], 'translation': [0, -2.5, 0], 'scale': [0.75, 0.75, 0.75]},
        'ground': {'translation': [0, 3, 0], 'scale': [0.4, 0.4, 0.4]},
        'fixed': {'rotation': [0, 180, 0], 'scale': [0.6, 0.6, 0.6]},
        'thirdperson_righthand': {'rotation': [75, 45, 0], 'translation': [0, 2.5, 0], 'scale': [0.375, 0.375, 0.375]},
        'firstperson_righthand': {'rotation': [0, 45, 0], 'scale': [0.4, 0.4, 0.4]},
    }
    return model


def write_json(path, data):
    with open(path, 'w', newline='\n') as f:
        json.dump(data, f, indent=2)
        f.write('\n')


def wood_texture(base, spread):
    """A placeholder: streaks of grain along the texture's rows, repeatable rather than random."""
    out = []
    for y in range(16):
        row = ((y * 7919) % 13) - 6
        for x in range(16):
            knot = -14 if (x * 31 + y * 17) % 97 == 0 else 0
            fleck = ((x * 2654435761 + y * 40503) >> 9) % 5 - 2
            shade = row * spread // 6 + fleck + knot
            out.append(tuple(max(0, min(255, c + shade)) for c in base))
    return out


def main():
    for material, (colour, spread) in MATERIALS.items():
        folder = os.path.join(MODEL_DIR, material)
        os.makedirs(folder, exist_ok=True)
        keep = set()
        for part in ARM_PARTS:
            keep.add(part + '.json')
            write_json(os.path.join(folder, part + '.json'), part_model(material, part))
        keep.add('item.json')
        write_json(os.path.join(folder, 'item.json'), item_model(material))
        for stale in os.listdir(folder):                     # the OBJ models these parts replaced
            if stale not in keep:
                os.remove(os.path.join(folder, stale))
        write_json(os.path.join(BLOCKSTATE_DIR, 'crossarm_%s.json' % material), multipart(material))
        write_json(os.path.join(ITEM_MODEL_DIR, 'crossarm_%s.json' % material),
                   {'parent': 'realgrid:block/crossarm/%s/item' % material})
        png(os.path.join(TEXTURE_DIR, 'crossarm_%s.png' % material), wood_texture(colour, spread))
    for kind in BRACES:
        folder = os.path.join(MODEL_DIR, 'brace_%s' % kind)
        os.makedirs(folder, exist_ok=True)
        for left in (False, True):
            for right in (False, True):
                write(os.path.join(folder, 'brace_%s.obj' % key(left, right, False)), brace_model(kind, left, right))
        write(os.path.join(folder, 'brace.mtl'), brace_mtl(kind))
        write(os.path.join(BLOCKSTATE_DIR, 'crossarm_brace_%s.json' % kind), json.dumps(brace_blockstate(kind), indent=2) + '\n')
    png(os.path.join(TEXTURE_DIR, 'crossarm_brace_wood.png'), wood_texture((150, 124, 92), 8))


if __name__ == '__main__':
    main()
