#!/usr/bin/env python3
"""Generates the placeholder models, blockstates and textures for the pole light mounts.

Run from the repository root:

    python scripts/gen_pole_light_mounts.py

Everything written here is placeholder geometry: a bracket plate, a brace and a tube arm. The
real models are meant to replace the .obj files one for one, keeping their names. The only
things the Java side relies on are the file names and the wire point, which lives in
TileEntityPoleLightMount (WIRE_POINT) and must agree with guide_insulator.obj below.

Coordinate system (the same one every generated .obj uses): one unit is one block, the mount
block spans 0..1 on every axis, the arm reaches NORTH (-Z), and the pole is on the SOUTH face
(z = 1). The blockstate rotates the model to the other three facings.

Arm reach: an arm of length L ends at the near edge of the block where its fixture goes, so a
fixture placed as its own block lines up with the tip.
  - straight: the fixture block is L blocks north of the mount.
  - left / right: the fixture block is n blocks north and n blocks west / east, n = round(L / sqrt 2).
    The arm aims at that block's centre, so it runs a little short of a true 45 degrees.
"""

import json
import math
import os
import struct
import zlib

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'main', 'resources', 'assets', 'realgrid')
MODEL_DIR = os.path.join(ROOT, 'models', 'block', 'pole_light_mount')
BLOCKSTATE_DIR = os.path.join(ROOT, 'blockstates')
TEXTURE_DIR = os.path.join(ROOT, 'textures', 'blocks')

LENGTHS = (2, 3, 4)
SWINGS = ('straight', 'left', 'right')

HEADER = '# Generated by scripts/gen_pole_light_mounts.py: placeholder geometry, replace with the final model.\n'

# Tube cross-section and heights, in blocks.
ARM_RADIUS = 0.05
BRACE_RADIUS = 0.03
TUBE_SIDES = 8
ARM_START_Y = 0.40      # where the arm leaves the bracket
ARM_TIP_Y = 0.85        # height of the arm at the fixture
ARM_RISE = 1.0          # horizontal distance over which the arm climbs from start to tip height
PIVOT = (0.5, 0.90)     # (x, z) where the arm leaves the bracket


class Obj:
    """Minimal OBJ writer: quads with per-face normals and a unit UV square per face."""

    def __init__(self, name, mtllib='pole_light_mount.mtl', header=HEADER):
        self.lines = [header, 'mtllib %s\n' % mtllib, 'o %s\n' % name,
                      'vt 0 0\n', 'vt 1 0\n', 'vt 1 1\n', 'vt 0 1\n']
        self.v = 0
        self.vn = 0
        self.material = None

    def use(self, material):
        if material != self.material:
            self.lines.append('usemtl %s\n' % material)
            self.material = material

    def quad(self, a, b, c, d):
        """Counter-clockwise when seen from outside."""
        n = _normalize(_cross(_sub(b, a), _sub(d, a)))
        for p in (a, b, c, d):
            self.lines.append('v %.6f %.6f %.6f\n' % p)
        self.lines.append('vn %.6f %.6f %.6f\n' % n)
        self.vn += 1
        i = self.v
        self.v += 4
        self.lines.append('f %d/1/%d %d/2/%d %d/3/%d %d/4/%d\n'
                          % (i + 1, self.vn, i + 2, self.vn, i + 3, self.vn, i + 4, self.vn))

    def box(self, lo, hi):
        x0, y0, z0 = lo
        x1, y1, z1 = hi
        self.quad((x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1))  # south
        self.quad((x1, y0, z0), (x0, y0, z0), (x0, y1, z0), (x1, y1, z0))  # north
        self.quad((x1, y0, z1), (x1, y0, z0), (x1, y1, z0), (x1, y1, z1))  # east
        self.quad((x0, y0, z0), (x0, y0, z1), (x0, y1, z1), (x0, y1, z0))  # west
        self.quad((x0, y1, z1), (x1, y1, z1), (x1, y1, z0), (x0, y1, z0))  # up
        self.quad((x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1))  # down

    def tube(self, points, radius, cap_end=True):
        """Sweeps a TUBE_SIDES-gon along a polyline, one ring per point."""
        rings = []
        for i, p in enumerate(points):
            if i == 0:
                t = _sub(points[1], p)
            elif i == len(points) - 1:
                t = _sub(p, points[i - 1])
            else:
                t = _add(_normalize(_sub(p, points[i - 1])), _normalize(_sub(points[i + 1], p)))
            t = _normalize(t)
            up = (0.0, 1.0, 0.0) if abs(t[1]) < 0.9 else (1.0, 0.0, 0.0)
            u = _normalize(_cross(t, up))
            w = _cross(u, t)
            ring = []
            for k in range(TUBE_SIDES):
                ang = 2 * math.pi * k / TUBE_SIDES
                off = _add(_scale(u, math.cos(ang) * radius), _scale(w, math.sin(ang) * radius))
                ring.append(_add(p, off))
            rings.append(ring)
        for r0, r1 in zip(rings, rings[1:]):
            for k in range(TUBE_SIDES):
                k1 = (k + 1) % TUBE_SIDES
                self.quad(r0[k], r1[k], r1[k1], r0[k1])
        if cap_end:
            end = rings[-1]
            for k in range(0, TUBE_SIDES - 2, 2):
                self.quad(end[0], end[(k + 3) % TUBE_SIDES], end[k + 2], end[k + 1])

    def text(self):
        return ''.join(self.lines)


def _add(a, b): return (a[0] + b[0], a[1] + b[1], a[2] + b[2])
def _sub(a, b): return (a[0] - b[0], a[1] - b[1], a[2] - b[2])
def _scale(a, s): return (a[0] * s, a[1] * s, a[2] * s)
def _cross(a, b): return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def _normalize(a):
    m = math.sqrt(a[0] ** 2 + a[1] ** 2 + a[2] ** 2) or 1.0
    return (a[0] / m, a[1] / m, a[2] / m)


def arm_end(length, swing):
    """(x, z) of the arm tip: the near edge of the fixture block, seen from the pivot."""
    if swing == 'straight':
        return (0.5, 1.0 - length)
    n = max(1, round(length / math.sqrt(2)))
    side = -1 if swing == 'left' else 1
    centre = (0.5 + side * n, 0.5 - n)
    dx, dz = centre[0] - PIVOT[0], centre[1] - PIVOT[1]
    d = math.hypot(dx, dz)
    return (centre[0] - 0.5 * dx / d, centre[1] - 0.5 * dz / d)


def arm_path(length, swing, samples=14):
    ex, ez = arm_end(length, swing)
    dx, dz = ex - PIVOT[0], ez - PIVOT[1]
    dist = math.hypot(dx, dz)
    pts = []
    for i in range(samples + 1):
        t = i / samples
        s = min(1.0, t * dist / ARM_RISE)
        y = ARM_START_Y + (ARM_TIP_Y - ARM_START_Y) * (1 - (1 - s) ** 2)
        pts.append((PIVOT[0] + dx * t, y, PIVOT[1] + dz * t))
    return pts


def arm_model(length, swing):
    obj = Obj('pole_light_mount_%d_%s' % (length, swing))
    obj.use('clamp')
    obj.box((0.3125, 0.125, 0.875), (0.6875, 0.875, 1.0))           # bracket plate on the pole
    obj.use('metal')
    path = arm_path(length, swing)
    obj.tube([(PIVOT[0], ARM_START_Y, 0.95)] + path, ARM_RADIUS)
    # Brace from the foot of the bracket up to the arm, about a third of a block out.
    reach = math.hypot(path[-1][0] - PIVOT[0], path[-1][2] - PIVOT[1])
    brace_to = path[max(1, int(round(len(path) * min(0.9, 0.7 / reach))))]
    obj.tube([(0.5, 0.16, 0.95), brace_to], BRACE_RADIUS)
    return obj.text()


def guide_insulator_model():
    """Drawn only once a wire is attached. Its front face is TileEntityPoleLightMount.WIRE_POINT."""
    obj = Obj('pole_light_mount_guide_insulator')
    obj.use('clamp')
    obj.box((0.46875, 0.75, 0.8125), (0.53125, 0.8125, 0.875))       # standoff off the bracket
    obj.use('porcelain')
    obj.box((0.4375, 0.8125, 0.75), (0.5625, 0.9375, 0.875))         # insulator body
    return obj.text()


MTL = HEADER + """newmtl metal
map_Kd realgrid:blocks/pole_light_mount_metal
newmtl clamp
map_Kd realgrid:blocks/pole_light_mount_clamp
newmtl porcelain
map_Kd realgrid:blocks/porcelain_insulators
"""


def blockstate(length):
    # The connector's 'base' is a plain resource location; a blockstate 'model' has block/ put in
    # front of it by Forge, so the submodel and inventory entries leave it off.
    base = lambda swing: 'realgrid:block/pole_light_mount/arm_%d_%s.obj' % (length, swing)
    item = 'realgrid:pole_light_mount/arm_%d_straight.obj' % length
    return {
        'forge_marker': 1,
        'defaults': {
            'model': 'immersiveengineering:smartmodel/connector',
            'custom': {'base': base('straight'), 'flip-v': True},
        },
        'variants': {
            'facing': {'north': {'y': 0}, 'east': {'y': 90}, 'south': {'y': 180}, 'west': {'y': 270}},
            'swing': {s: {'custom': {'base': base(s)}} for s in SWINGS},
            'wired': {
                # Not an empty object: an empty forge_marker variant renders as the missing model.
                'false': {'custom': {'flip-v': True}},
                'true': {'submodel': {'guide_insulator': {
                    'model': 'realgrid:pole_light_mount/guide_insulator.obj',
                    'custom': {'flip-v': True}}}},
            },
            'inventory': [{
                'model': item,
                'custom': {'flip-v': True},
                'transform': {
                    'gui': {'translation': [0.1, -0.05, 0], 'rotation': [{'x': 30}, {'y': 135}], 'scale': 0.32},
                    'ground': {'translation': [0, 0.1, 0], 'scale': 0.2},
                    'fixed': {'rotation': [{'y': 180}], 'scale': 0.3},
                    'thirdperson': {'translation': [0, 0.1, 0.1], 'rotation': [{'x': 75}, {'y': 45}], 'scale': 0.25},
                    'firstperson': {'translation': [0.1, 0.1, 0], 'rotation': [{'y': 45}], 'scale': 0.25},
                },
            }],
        },
    }


def png(path, pixels, size=16):
    raw = b''.join(b'\x00' + bytes(v for px in pixels[y * size:(y + 1) * size] for v in px) for y in range(size))
    chunk = lambda tag, data: struct.pack('>I', len(data)) + tag + data + struct.pack('>I', zlib.crc32(tag + data) & 0xffffffff)
    with open(path, 'wb') as f:
        f.write(b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', size, size, 8, 2, 0, 0, 0))
                + chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b''))


def textured(base, spread):
    """A flat colour with a fixed, repeatable speckle so the placeholder does not read as untextured."""
    out = []
    for i in range(256):
        jitter = ((i * 2654435761) >> 7) % (2 * spread + 1) - spread
        out.append(tuple(max(0, min(255, c + jitter)) for c in base))
    return out


def write(path, text):
    with open(path, 'w', newline='\n') as f:
        f.write(text)


def main():
    os.makedirs(MODEL_DIR, exist_ok=True)
    for length in LENGTHS:
        for swing in SWINGS:
            write(os.path.join(MODEL_DIR, 'arm_%d_%s.obj' % (length, swing)), arm_model(length, swing))
        write(os.path.join(BLOCKSTATE_DIR, 'pole_light_mount_%d.json' % length),
              json.dumps(blockstate(length), indent=2) + '\n')
    write(os.path.join(MODEL_DIR, 'guide_insulator.obj'), guide_insulator_model())
    write(os.path.join(MODEL_DIR, 'pole_light_mount.mtl'), MTL)
    png(os.path.join(TEXTURE_DIR, 'pole_light_mount_metal.png'), textured((168, 172, 170), 6))
    png(os.path.join(TEXTURE_DIR, 'pole_light_mount_clamp.png'), textured((40, 40, 42), 4))


if __name__ == '__main__':
    main()
