#!/usr/bin/env python3
"""Generates the models, blockstates and textures for the pole light mounts.

Run from the repository root:

    python scripts/gen_pole_light_mounts.py

The arm follows the SCE / LADWP street-light arms in issue #34: a plate bolted to the pole with a
mast-arm fitting, a round arm that leaves the fitting level, sweeps up through an elbow and runs
out on a gentle rise, a slimmer slip-fitter at the tip for the fixture, and a diagonal brace. Once
a wire is attached ("wired" models) a porcelain guide insulator sits on top of the plate and the
supply cable drops from it, hangs about 13 pixels under the arm and meets the arm at the tip.

The Java side relies only on the file names and on the wire point, which lives in
TileEntityPoleLightMount (WIRE_POINT) and must agree with GUIDE_FRONT below.

Coordinate system (the same one every generated .obj uses): one unit is one block, the mount
block spans 0..1 on every axis, the arm reaches NORTH (-Z), and the pole is on the SOUTH face
(z = 1). The blockstate rotates the model to the other three facings.

Arm reach: the fixture is placed as its own block, one block above the mount, facing the same way
as the arm. CSM's street-light fixtures (Cree LEDway, Sylvania, Sears) sit in the bottom of their
block with the arm socket in the middle of the back face, about 1 to 4 px up, so the arm ends
there and runs a little way into the socket:
  - straight: the fixture block is L blocks north of the mount.
  - left / right: the fixture block is n blocks north and n blocks west / east, n = round(L / sqrt 2).
    CSM fixtures only face the four sides, so a swung arm curves round to run straight north into
    the socket rather than meeting the fixture's corner at 45 degrees.
"""

import json
import math
import os
import struct
import zlib

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'main', 'resources', 'assets', 'realgrid')
MODEL_DIR = os.path.join(ROOT, 'models', 'block', 'pole_light_mount')
BLOCKSTATE_DIR = os.path.join(ROOT, 'blockstates')
TEXTURE_DIR = os.path.join(ROOT, 'textures', 'blocks')

LENGTHS = tuple(range(1, 9))
SWINGS = ('straight', 'left', 'right')
FACINGS = (('north', 0), ('east', 90), ('south', 180), ('west', 270))

HEADER = '# Generated by scripts/gen_pole_light_mounts.py\n'

PX = 1 / 16
TUBE_SIDES = 8
ARM_SIDES = 12
ARM_RADIUS = 0.045
TIP_RADIUS = 0.034      # slip-fitter the fixture clamps onto
BRACE_RADIUS = 0.022
CABLE_RADIUS = 0.017
PIVOT = (0.5, 0.80)     # (x, z) where the arm leaves the fitting
ARM_START_Y = 0.41      # height of the arm leaving the fitting
ELBOW_TOP_Y = 0.70      # height at the top of the elbow
ARM_TIP_Y = 1 + 2.5 * PX  # height of the slip-fitter: a CSM fixture's socket, one block up
TIP_LENGTH = 0.18       # level slip-fitter at the tip
TIP_INSET = 3 * PX      # how far the slip-fitter runs into the fixture's socket
SWING_TURN = 0.7        # how far back from the socket a swung arm starts turning to meet it
CABLE_DROP = 13 * PX    # how far the cable hangs under the arm at its lowest
GUIDE_FRONT = (0.5, 0.875, 0.75)   # front face of the guide insulator = TileEntityPoleLightMount.WIRE_POINT


class Obj:
    """Minimal OBJ writer: quads with per-face normals and a unit UV square per face."""

    def __init__(self, name, mtllib='pole_light_mount.mtl', header=HEADER):
        self.lines = [header, 'mtllib %s\n' % mtllib, 'o %s\n' % name,
                      'vt 0 0\n', 'vt 1 0\n', 'vt 1 1\n', 'vt 0 1\n']
        self.v = 0
        self.vn = 0
        self.material = None

    def use(self, material):
        if material != self.material:
            self.lines.append('usemtl %s\n' % material)
            self.material = material

    def quad(self, a, b, c, d):
        """Counter-clockwise when seen from outside."""
        n = _normalize(_cross(_sub(b, a), _sub(d, a)))
        for p in (a, b, c, d):
            self.lines.append('v %.6f %.6f %.6f\n' % p)
        self.lines.append('vn %.6f %.6f %.6f\n' % n)
        self.vn += 1
        i = self.v
        self.v += 4
        self.lines.append('f %d/1/%d %d/2/%d %d/3/%d %d/4/%d\n'
                          % (i + 1, self.vn, i + 2, self.vn, i + 3, self.vn, i + 4, self.vn))

    def box(self, lo, hi):
        x0, y0, z0 = lo
        x1, y1, z1 = hi
        self.quad((x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1))  # south
        self.quad((x1, y0, z0), (x0, y0, z0), (x0, y1, z0), (x1, y1, z0))  # north
        self.quad((x1, y0, z1), (x1, y0, z0), (x1, y1, z0), (x1, y1, z1))  # east
        self.quad((x0, y0, z0), (x0, y0, z1), (x0, y1, z1), (x0, y1, z0))  # west
        self.quad((x0, y1, z1), (x1, y1, z1), (x1, y1, z0), (x0, y1, z0))  # up
        self.quad((x0, y0, z0), (x1, y0, z0), (x1, y0, z1), (x0, y0, z1))  # down

    def tube(self, points, radius, cap_end=True, sides=TUBE_SIDES):
        """Sweeps a regular polygon along a polyline, one ring per point."""
        rings = []
        for i, p in enumerate(points):
            if i == 0:
                t = _sub(points[1], p)
            elif i == len(points) - 1:
                t = _sub(p, points[i - 1])
            else:
                t = _add(_normalize(_sub(p, points[i - 1])), _normalize(_sub(points[i + 1], p)))
            t = _normalize(t)
            up = (0.0, 1.0, 0.0) if abs(t[1]) < 0.9 else (1.0, 0.0, 0.0)
            u = _normalize(_cross(t, up))
            w = _cross(u, t)
            ring = []
            for k in range(sides):
                ang = 2 * math.pi * k / sides
                off = _add(_scale(u, math.cos(ang) * radius), _scale(w, math.sin(ang) * radius))
                ring.append(_add(p, off))
            rings.append(ring)
        for r0, r1 in zip(rings, rings[1:]):
            for k in range(sides):
                k1 = (k + 1) % sides
                self.quad(r0[k], r1[k], r1[k1], r0[k1])
        if cap_end:
            end = rings[-1]
            for k in range(0, sides - 2, 2):
                self.quad(end[0], end[(k + 3) % sides], end[k + 2], end[k + 1])

    def text(self):
        return ''.join(self.lines)


def _add(a, b): return (a[0] + b[0], a[1] + b[1], a[2] + b[2])
def _sub(a, b): return (a[0] - b[0], a[1] - b[1], a[2] - b[2])
def _scale(a, s): return (a[0] * s, a[1] * s, a[2] * s)
def _cross(a, b): return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def _normalize(a):
    m = math.sqrt(a[0] ** 2 + a[1] ** 2 + a[2] ** 2) or 1.0
    return (a[0] / m, a[1] / m, a[2] / m)


def arm_route(length, swing):
    """The arm's course seen from above, as (x, z) points from the pivot to the tip. The tip is
    TIP_INSET into the socket on the back face of the fixture block."""
    if swing == 'straight':
        return [PIVOT, (0.5, 1.0 - length - TIP_INSET)]
    n = max(1, round(length / math.sqrt(2)))
    side = -1 if swing == 'left' else 1
    sx, sz = 0.5 + side * n, 1.0 - n - TIP_INSET
    # Quadratic Bezier whose control point is straight behind the socket, so the arm leaves the
    # pivot heading for the fixture and arrives heading north.
    cx, cz = sx, sz + SWING_TURN
    pts = []
    for i in range(41):
        t = i / 40
        a, b, c = (1 - t) ** 2, 2 * (1 - t) * t, t ** 2
        pts.append((a * PIVOT[0] + b * cx + c * sx, a * PIVOT[1] + b * cz + c * sz))
    return pts


class ArmPath:
    """Height of the arm as a function of horizontal distance s from the pivot, along its route."""

    def __init__(self, length, swing):
        self.route = arm_route(length, swing)
        self.dist = [0.0]
        for a, b in zip(self.route, self.route[1:]):
            self.dist.append(self.dist[-1] + math.hypot(b[0] - a[0], b[1] - a[1]))
        self.reach = self.dist[-1]
        d = self.reach
        self.s_level = min(0.12, 0.1 * d)                      # level run out of the fitting
        self.s_elbow = self.s_level + min(0.7, 0.45 * d)       # top of the elbow
        self.s_tip = d - min(TIP_LENGTH, 0.2 * d)              # start of the slip-fitter

    def y(self, s):
        if s <= self.s_level:
            return ARM_START_Y
        if s <= self.s_elbow:
            u = (s - self.s_level) / (self.s_elbow - self.s_level)
            return ARM_START_Y + (ELBOW_TOP_Y - ARM_START_Y) * math.sin(u * math.pi / 2) ** 2
        if s <= self.s_tip:
            u = (s - self.s_elbow) / max(1e-6, self.s_tip - self.s_elbow)
            return ELBOW_TOP_Y + (ARM_TIP_Y - ELBOW_TOP_Y) * u
        return ARM_TIP_Y

    def point(self, s, dy=0.0):
        s = max(0.0, min(self.reach, s))
        i = 1
        while i < len(self.dist) - 1 and self.dist[i] < s:
            i += 1
        a, b = self.route[i - 1], self.route[i]
        span = self.dist[i] - self.dist[i - 1]
        f = (s - self.dist[i - 1]) / span if span else 0.0
        return (a[0] + (b[0] - a[0]) * f, self.y(s) + dy, a[1] + (b[1] - a[1]) * f)


def _samples(a, b, n):
    return [a + (b - a) * i / n for i in range(n + 1)]


def arm_model(length, swing, wired):
    path = ArmPath(length, swing)
    obj = Obj('pole_light_mount_%d_%s%s' % (length, swing, '_wired' if wired else ''))
    obj.use('clamp')
    obj.box((5 * PX, 1 * PX, 0.9), (11 * PX, 15 * PX, 1.0))              # plate bolted to the pole
    obj.box((6.5 * PX, 5 * PX, PIVOT[1]), (9.5 * PX, 8.5 * PX, 0.9))      # mast-arm fitting
    for y in (2.5 * PX, 13.5 * PX):                                        # through-bolt heads
        obj.box((7.5 * PX, y - 0.5 * PX, 0.88), (8.5 * PX, y + 0.5 * PX, 0.9))
    obj.use('metal')
    ss = ([0.0] + _samples(path.s_level, path.s_elbow, 10)
          + _samples(path.s_elbow, path.s_tip, 1 if swing == 'straight' else max(1, round(3 * path.reach)))[1:])
    obj.tube([(PIVOT[0], ARM_START_Y, 0.86)] + [path.point(s) for s in ss], ARM_RADIUS, sides=ARM_SIDES)
    obj.tube([path.point(s) for s in _samples(path.s_tip - 0.01, path.reach, 3)], TIP_RADIUS, sides=ARM_SIDES)
    brace_s = min(0.9, 0.55 * path.reach)
    obj.tube([(0.5, 2 * PX, 0.89), path.point(brace_s, -ARM_RADIUS * 0.6)], BRACE_RADIUS, sides=TUBE_SIDES)
    if wired:
        obj.use('clamp')
        obj.box((7.5 * PX, 0.75, 0.8125), (8.5 * PX, 0.8125, 0.9))            # insulator standoff
        obj.use('porcelain')
        obj.box((7 * PX, 0.8125, GUIDE_FRONT[2]), (9 * PX, 0.9375, 0.875))    # guide insulator
        obj.use('cable')
        pts = [GUIDE_FRONT]
        for s in _samples(0.0, path.reach, 24)[1:]:
            w = min(1.0, s / 0.35)
            arm_pt = path.point(s)
            hang = CABLE_DROP * max(0.0, math.sin(math.pi * s / path.reach)) ** 0.6
            y = (1 - w) * GUIDE_FRONT[1] + w * (arm_pt[1] - ARM_RADIUS) - hang
            pts.append((arm_pt[0], y, arm_pt[2]))
        obj.tube(pts, CABLE_RADIUS, sides=6)
    return obj.text()


MTL = HEADER + """newmtl metal
map_Kd realgrid:blocks/pole_light_mount_metal
newmtl clamp
map_Kd realgrid:blocks/pole_light_mount_clamp
newmtl porcelain
map_Kd realgrid:blocks/porcelain_insulators
newmtl cable
map_Kd realgrid:blocks/pole_light_mount_cable
"""


def blockstate(length):
    """Every facing/swing/wired combination is listed: the wired models differ per swing (the cable
    follows the arm), which per-property variants cannot express."""
    def base(swing, wired):
        return 'realgrid:block/pole_light_mount/arm_%d_%s%s.obj' % (length, swing, '_wired' if wired else '')
    variants = {}
    for facing, y in FACINGS:
        for swing in SWINGS:
            for wired in (False, True):
                variants['facing=%s,swing=%s,wired=%s' % (facing, swing, str(wired).lower())] = {
                    'model': 'immersiveengineering:smartmodel/connector',
                    'custom': {'base': base(swing, wired), 'flip-v': True},
                    'y': y,
                }
    # A blockstate 'model' has block/ put in front of it by Forge, so the inventory entry leaves it off.
    item = 'realgrid:pole_light_mount/arm_%d_straight.obj' % length
    scale = round(0.9 / (length + 1.2), 3)
    variants['inventory'] = {
        'model': item,
        'custom': {'flip-v': True},
        'transform': {
            'gui': {'translation': [0.1, -0.05, 0], 'rotation': [{'x': 30}, {'y': 135}], 'scale': scale},
            'ground': {'translation': [0, 0.1, 0], 'scale': round(scale * 0.6, 3)},
            'fixed': {'rotation': [{'y': 180}], 'scale': scale},
            'thirdperson': {'translation': [0, 0.1, 0.1], 'rotation': [{'x': 75}, {'y': 45}], 'scale': round(scale * 0.8, 3)},
            'firstperson': {'translation': [0.1, 0.1, 0], 'rotation': [{'y': 45}], 'scale': round(scale * 0.8, 3)},
        },
    }
    return {'forge_marker': 1, 'variants': variants}


def png(path, pixels, size=16):
    raw = b''.join(b'\x00' + bytes(v for px in pixels[y * size:(y + 1) * size] for v in px) for y in range(size))
    chunk = lambda tag, data: struct.pack('>I', len(data)) + tag + data + struct.pack('>I', zlib.crc32(tag + data) & 0xffffffff)
    with open(path, 'wb') as f:
        f.write(b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', size, size, 8, 2, 0, 0, 0))
                + chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b''))


def textured(base, spread):
    """A flat colour with a fixed, repeatable speckle so the placeholder does not read as untextured."""
    out = []
    for i in range(256):
        jitter = ((i * 2654435761) >> 7) % (2 * spread + 1) - spread
        out.append(tuple(max(0, min(255, c + jitter)) for c in base))
    return out


def write(path, text):
    with open(path, 'w', newline='\n') as f:
        f.write(text)


def main():
    os.makedirs(MODEL_DIR, exist_ok=True)
    keep = set()
    for length in LENGTHS:
        for swing in SWINGS:
            for wired in (False, True):
                name = 'arm_%d_%s%s.obj' % (length, swing, '_wired' if wired else '')
                keep.add(name)
                write(os.path.join(MODEL_DIR, name), arm_model(length, swing, wired))
        write(os.path.join(BLOCKSTATE_DIR, 'pole_light_mount_%d.json' % length),
              json.dumps(blockstate(length), indent=2) + '\n')
    for stale in os.listdir(MODEL_DIR):
        if stale.endswith('.obj') and stale not in keep:
            os.remove(os.path.join(MODEL_DIR, stale))
    write(os.path.join(MODEL_DIR, 'pole_light_mount.mtl'), MTL)
    png(os.path.join(TEXTURE_DIR, 'pole_light_mount_metal.png'), textured((168, 172, 170), 6))
    png(os.path.join(TEXTURE_DIR, 'pole_light_mount_clamp.png'), textured((40, 40, 42), 4))
    png(os.path.join(TEXTURE_DIR, 'pole_light_mount_cable.png'), textured((22, 22, 24), 3))


if __name__ == '__main__':
    main()
