#!/usr/bin/env python3
"""Generates the placeholder models and blockstates for the transformer bank mounts.

Run from the repository root:

    python scripts/gen_transformer_bank_mounts.py

Placeholder geometry: two steel channels and a pole strap, meant to be replaced by the final
models file for file. Only the file names are relied on by the Java side.

Coordinate system (as in gen_pole_light_mounts.py): one unit is one block, the mount block spans
0..1, the mount faces NORTH and the pole is the block to its SOUTH (z 1..2). The model reaches one
block either side (x -1..2) and one block up (y 0..2), because it spans a whole bank of two-block
transformers.

Transformers sit flush against a log pole (a RealGrid transformer's back lugs are at its cell's
edge), so the mount cannot go between tank and pole. It goes on a face of the pole instead, and
its channels run across that face at the tanks' lug heights (3-9 and 23-29 pixels of a transformer
standing on the same level as the mount):

  - three-transformer bank: tanks on the pole's other three faces. The channels run across the
    pole's front and wrap onto the two side tanks.
  - two-transformer bank: two tanks side by side in the cells left and right of the mount, facing
    away from the pole, backs against the channels.
"""

import json
import os

from gen_pole_light_mounts import Obj, png, textured, write

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'main', 'resources', 'assets', 'realgrid')
MODEL_DIR = os.path.join(ROOT, 'models', 'block', 'transformer_bank_mount')
BLOCKSTATE_DIR = os.path.join(ROOT, 'blockstates')

HEADER = '# Generated by scripts/gen_transformer_bank_mounts.py: placeholder geometry, replace with the final model.\n'

PX = 1 / 16
LUG_BANDS = ((3 * PX, 9 * PX), (23 * PX, 29 * PX))   # transformer back-lug heights
CHANNEL_Z = (1 - 2 * PX, 1.0)                        # against the pole face, 2 px deep


def channel(obj, y0, y1, x0=-1.0, x1=2.0):
    """A C-channel along x: a web against the pole and two flanges pointing away from it."""
    z0, z1 = CHANNEL_Z
    obj.box((x0, y0, z1 - PX / 2), (x1, y1, z1))              # web
    obj.box((x0, y0, z0), (x1, y0 + PX, z1 - PX / 2))         # bottom flange
    obj.box((x0, y1 - PX, z0), (x1, y1, z1 - PX / 2))         # top flange


def mount_model(transformers):
    obj = Obj('transformer_bank_mount_%d' % transformers, 'transformer_bank_mount.mtl', HEADER)
    obj.use('metal')
    for y0, y1 in LUG_BANDS:
        channel(obj, y0, y1)
    obj.use('clamp')
    # Pole strap holding both channels, bolted through the pole.
    obj.box((7 * PX, 0.0, CHANNEL_Z[0] - PX), (9 * PX, 2.0, CHANNEL_Z[0]))
    if transformers == 3:
        # The side tanks stand on the pole's east and west faces; clamp round their front corners.
        for y0, y1 in LUG_BANDS:
            obj.box((-1.0 - PX, y0, CHANNEL_Z[0]), (-1.0, y1, 1.0 + 6 * PX))
            obj.box((2.0, y0, CHANNEL_Z[0]), (2.0 + PX, y1, 1.0 + 6 * PX))
    return obj.text()


MTL = HEADER + """newmtl metal
map_Kd realgrid:blocks/pole_light_mount_metal
newmtl clamp
map_Kd realgrid:blocks/pole_light_mount_clamp
"""


def blockstate(transformers):
    model = 'realgrid:transformer_bank_mount/mount_%d.obj' % transformers
    return {
        'forge_marker': 1,
        'defaults': {'model': model, 'custom': {'flip-v': True}},
        'variants': {
            'facing': {'north': {'y': 0}, 'east': {'y': 90}, 'south': {'y': 180}, 'west': {'y': 270}},
            'inventory': [{
                'model': model,
                'custom': {'flip-v': True},
                'transform': {
                    'gui': {'translation': [0, -0.1, 0], 'rotation': [{'x': 30}, {'y': 135}], 'scale': 0.28},
                    'ground': {'translation': [0, 0.1, 0], 'scale': 0.2},
                    'fixed': {'rotation': [{'y': 180}], 'scale': 0.3},
                    'thirdperson': {'translation': [0, 0.1, 0.1], 'rotation': [{'x': 75}, {'y': 45}], 'scale': 0.25},
                    'firstperson': {'translation': [0.1, 0.1, 0], 'rotation': [{'y': 45}], 'scale': 0.25},
                },
            }],
        },
    }


def main():
    os.makedirs(MODEL_DIR, exist_ok=True)
    for transformers in (2, 3):
        write(os.path.join(MODEL_DIR, 'mount_%d.obj' % transformers), mount_model(transformers))
        write(os.path.join(BLOCKSTATE_DIR, 'transformer_bank_mount_%d.json' % transformers),
              json.dumps(blockstate(transformers), indent=2) + '\n')
    write(os.path.join(MODEL_DIR, 'transformer_bank_mount.mtl'), MTL)


if __name__ == '__main__':
    main()
