#!/usr/bin/env python3
"""Generates the placeholder models and blockstates for the transformer bank mounts.

Run from the repository root:

    python scripts/gen_transformer_bank_mounts.py

Placeholder geometry, meant to be replaced by the final models file for file. Only the file names
are relied on by the Java side.

Coordinate system (as in gen_pole_light_mounts.py): one unit is one block, the mount block spans
0..1, the mount faces NORTH and the pole is the block to its SOUTH (z 1..2). The frame is two
blocks tall (y 0..2), like the transformers it carries.

The mount is a steel box frame standing off the front of the pole; the back of the pole is left
for bolt covers. Transformers stand flush against the frame the same way they stand flush against
a log, their back lugs at the edge of the frame's block:

  - three-transformer bank: one tank on each side of the frame, facing outwards, and one on its
    front, facing away from the pole.
      * LADWP: X-braced side frames.
      * SCE:   straight side arms.
  - two-transformer bank: a smaller frame with one tank on each side.
"""

import json
import os

from gen_pole_light_mounts import Obj, write

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'main', 'resources', 'assets', 'realgrid')
MODEL_DIR = os.path.join(ROOT, 'models', 'block', 'transformer_bank_mount')
BLOCKSTATE_DIR = os.path.join(ROOT, 'blockstates')

HEADER = '# Generated by scripts/gen_transformer_bank_mounts.py: placeholder geometry, replace with the final model.\n'

PX = 1 / 16
LUG_BANDS = ((3 * PX, 9 * PX), (23 * PX, 29 * PX))   # transformer back-lug heights
BAR = 1.5 * PX                                       # square steel section
BRACE = 0.02                                         # diagonal brace radius

VARIANTS = {
    # registry suffix: (transformers, side style, frame top)
    'ladwp_3': (3, 'x', 2.0),
    'sce_3': (3, 'straight', 2.0),
    '2': (2, 'straight', 29 * PX + BAR),
}


def rail_x(obj, y0, y1, z0, z1):
    """Horizontal member across the frame (along x) at a lug band."""
    obj.box((0.0, y0, z0), (1.0, y0 + BAR, z1))
    obj.box((0.0, y1 - BAR, z0), (1.0, y1, z1))


def side(obj, x0, x1, style, top):
    """One side frame: corner posts, a rail at each lug band, and the side's bracing."""
    obj.box((x0, 0.0, 0.0), (x1, top, BAR))                      # front post
    obj.box((x0, 0.0, 1.0 - BAR), (x1, top, 1.0))                # post against the pole
    for y0, y1 in LUG_BANDS:
        obj.box((x0, y0, 0.0), (x1, y0 + BAR, 1.0))
        obj.box((x0, y1 - BAR, 0.0), (x1, y1, 1.0))
    xm = (x0 + x1) / 2
    if style == 'x':
        lo, hi = LUG_BANDS[0][0], LUG_BANDS[1][1]
        obj.tube([(xm, lo, BAR), (xm, hi, 1.0 - BAR)], BRACE)
        obj.tube([(xm, lo, 1.0 - BAR), (xm, hi, BAR)], BRACE)
    else:
        # A straight arm from the pole out to the front post, midway up.
        ym = (LUG_BANDS[0][1] + LUG_BANDS[1][0]) / 2
        obj.box((x0, ym - BAR / 2, 0.0), (x1, ym + BAR / 2, 1.0))


def mount_model(name, transformers, style, top):
    obj = Obj('transformer_bank_mount_%s' % name, 'transformer_bank_mount.mtl', HEADER)
    obj.use('metal')
    side(obj, 0.0, BAR, style, top)
    side(obj, 1.0 - BAR, 1.0, style, top)
    for y0, y1 in LUG_BANDS:
        rail_x(obj, y0, y1, 1.0 - BAR, 1.0)        # back rails, bolted to the pole
        if transformers == 3:
            rail_x(obj, y0, y1, 0.0, BAR)          # front rails, carrying the front tank
    obj.use('clamp')
    # Pole plate the back rails bolt through.
    obj.box((5 * PX, 0.0, 1.0 - BAR - PX / 2), (11 * PX, top, 1.0 - BAR))
    return obj.text()


MTL = HEADER + """newmtl metal
map_Kd realgrid:blocks/pole_light_mount_metal
newmtl clamp
map_Kd realgrid:blocks/pole_light_mount_clamp
"""


def blockstate(name):
    model = 'realgrid:transformer_bank_mount/mount_%s.obj' % name
    return {
        'forge_marker': 1,
        'defaults': {'model': model, 'custom': {'flip-v': True}},
        'variants': {
            'facing': {'north': {'y': 0}, 'east': {'y': 90}, 'south': {'y': 180}, 'west': {'y': 270}},
            'inventory': [{
                'model': model,
                'custom': {'flip-v': True},
                'transform': {
                    'gui': {'translation': [0, -0.2, 0], 'rotation': [{'x': 30}, {'y': 135}], 'scale': 0.4},
                    'ground': {'translation': [0, 0.1, 0], 'scale': 0.25},
                    'fixed': {'rotation': [{'y': 180}], 'scale': 0.4},
                    'thirdperson': {'translation': [0, 0.1, 0.1], 'rotation': [{'x': 75}, {'y': 45}], 'scale': 0.3},
                    'firstperson': {'translation': [0.1, 0.1, 0], 'rotation': [{'y': 45}], 'scale': 0.3},
                },
            }],
        },
    }


def main():
    os.makedirs(MODEL_DIR, exist_ok=True)
    for old in ('mount_2.obj', 'mount_3.obj'):
        path = os.path.join(MODEL_DIR, old)
        if os.path.exists(path) and old[:-4] not in ['mount_%s' % n for n in VARIANTS]:
            os.remove(path)
    for name, (transformers, style, top) in VARIANTS.items():
        write(os.path.join(MODEL_DIR, 'mount_%s.obj' % name), mount_model(name, transformers, style, top))
        write(os.path.join(BLOCKSTATE_DIR, 'transformer_bank_mount_%s.json' % name),
              json.dumps(blockstate(name), indent=2) + '\n')
    write(os.path.join(MODEL_DIR, 'transformer_bank_mount.mtl'), MTL)


if __name__ == '__main__':
    main()
