#!/usr/bin/env python3
"""Generates the models, blockstates and placeholder textures for the transformer cases (issue #38).

Run from the repository root:

    python scripts/gen_transformer_cases.py

A transformer case (BlockTransformerCase) is one square of a platform that transformers stand on.
Each block's model is put together by a multipart blockstate from its state: the deck at the top of
the block (13-16 px, so a transformer stands in the block above) with a joist under it, and on each
open side (north, east, south or west false: no case of the same kind and no pole there) a framing
beam under the deck's edge and, while `railings` is on, a railing above it reaching into the block
above. The side parts are drawn for the north side and turned to the others by the blockstate.
"""

import json
import os

import model_uv
from gen_pole_light_mounts import png, textured

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'main', 'resources', 'assets', 'realgrid')
MODEL_DIR = os.path.join(ROOT, 'models', 'block', 'transformer_case')
BLOCKSTATE_DIR = os.path.join(ROOT, 'blockstates')
ITEM_MODEL_DIR = os.path.join(ROOT, 'models', 'item')
TEXTURE_DIR = os.path.join(ROOT, 'textures', 'blocks')

GALVANIZED = 'realgrid:blocks/crossarm_galvanized'      # written by gen_crossarms.py
WOOD = 'realgrid:blocks/crossarm_brace_wood'            # likewise

# kind: (deck texture, frame and railing texture)
KINDS = {
    'metal': ('realgrid:blocks/transformer_case_grating', GALVANIZED),
    'wood': ('realgrid:blocks/transformer_case_planks', WOOD),
}
SIDES = (('north', 0), ('east', 90), ('south', 180), ('west', 270))

PARTS = {
    # The deck and a joist across under its middle.
    'deck': ('deck', [((0, 13, 0), (16, 16, 16))]),
    'joist': ('frame', [((0, 10, 7), (16, 13, 9))]),
    # An open north edge: a beam under the deck, and a railing above (two posts, top and middle rails).
    'frame_side': ('frame', [((0, 9, 0), (16, 13, 2))]),
    'rail_side': ('frame', [((0, 16, 0), (1.5, 30, 1.5)), ((14.5, 16, 0), (16, 30, 1.5)),
                            ((0, 28.5, 0), (16, 30, 1.5)), ((0, 22, 0.25), (16, 23.25, 1.25))]),
}


def model(kind, part):
    deck, frame = KINDS[kind]
    var, boxes = PARTS[part]
    elements = [{'from': list(lo), 'to': list(hi), 'faces': model_uv.faces(lo, hi, '#' + var)} for lo, hi in boxes]
    return {'__comment': 'Generated by scripts/gen_transformer_cases.py',
            'textures': {var: deck if var == 'deck' else frame, 'particle': deck}, 'elements': elements}


def blockstate(kind):
    base = 'realgrid:transformer_case/%s/' % kind
    parts = [{'apply': {'model': base + 'deck'}}, {'apply': {'model': base + 'joist'}}]
    for side, y in SIDES:
        parts.append({'when': {side: 'false'}, 'apply': {'model': base + 'frame_side', 'y': y}})
        parts.append({'when': {side: 'false', 'railings': 'true'}, 'apply': {'model': base + 'rail_side', 'y': y}})
    return {'multipart': parts}


def item(kind):
    """One square with its frame and railings all round, as it stands alone."""
    deck, frame = KINDS[kind]
    elements = []
    for part in ('deck', 'joist'):
        elements += model(kind, part)['elements']
    for side, y in SIDES:
        for part in ('frame_side', 'rail_side'):
            for e in model(kind, part)['elements']:
                elements.append(rotated(e, y))
    return {'__comment': 'Generated by scripts/gen_transformer_cases.py',
            'textures': {'deck': deck, 'frame': frame, 'particle': deck}, 'elements': elements,
            'display': {'gui': {'rotation': [30, 225, 0], 'translation': [0, -3, 0], 'scale': [0.5, 0.5, 0.5]},
                        'ground': {'scale': [0.3, 0.3, 0.3]},
                        'thirdperson_righthand': {'rotation': [75, 45, 0], 'scale': [0.3, 0.3, 0.3]},
                        'firstperson_righthand': {'rotation': [0, 45, 0], 'scale': [0.35, 0.35, 0.35]}}}


def rotated(element, y):
    """An element turned clockwise (seen from above) by y degrees about the block's centre."""
    lo, hi = element['from'], element['to']
    corners = [(lo[0], lo[2]), (hi[0], hi[2])]
    for _ in range((y // 90) % 4):
        corners = [(16 - z, x) for x, z in corners]
    xs, zs = [c[0] for c in corners], [c[1] for c in corners]
    new_lo, new_hi = [min(xs), lo[1], min(zs)], [max(xs), hi[1], max(zs)]
    texture = next(iter(element['faces'].values()))['texture']
    return {'from': new_lo, 'to': new_hi, 'faces': model_uv.faces(new_lo, new_hi, texture)}


def grating():
    """Steel grating: a light grid of bars over dark gaps."""
    out = []
    for y in range(16):
        for x in range(16):
            bar = x % 4 == 0 or y % 4 == 0
            base = (150, 154, 154) if bar else (52, 54, 56)
            jitter = ((x * 2654435761 + y * 40503) >> 9) % 7 - 3
            out.append(tuple(max(0, min(255, c + jitter)) for c in base))
    return out


def planks():
    """Weathered deck planks running across the deck, with dark joints between them."""
    out = []
    for y in range(16):
        for x in range(16):
            if y % 4 == 3:
                c = (70, 56, 40)
            else:
                tone = ((y // 4) * 37 % 5 - 2) * 6
                grain = ((x * 7 + y * 13) % 11) - 5
                c = (138 + tone + grain, 112 + tone + grain, 82 + tone + grain)
            out.append(tuple(max(0, min(255, v)) for v in c))
    return out


def write_json(path, data):
    with open(path, 'w', newline='\n') as f:
        json.dump(data, f, indent=2)
        f.write('\n')


def main():
    for kind in KINDS:
        folder = os.path.join(MODEL_DIR, kind)
        os.makedirs(folder, exist_ok=True)
        for part in PARTS:
            write_json(os.path.join(folder, part + '.json'), model(kind, part))
        write_json(os.path.join(folder, 'item.json'), item(kind))
        write_json(os.path.join(BLOCKSTATE_DIR, 'transformer_case_%s.json' % kind), blockstate(kind))
        write_json(os.path.join(ITEM_MODEL_DIR, 'transformer_case_%s.json' % kind),
                   {'parent': 'realgrid:block/transformer_case/%s/item' % kind})
    png(os.path.join(TEXTURE_DIR, 'transformer_case_grating.png'), grating())
    png(os.path.join(TEXTURE_DIR, 'transformer_case_planks.png'), planks())


if __name__ == '__main__':
    main()
