#!/usr/bin/env python3
"""Generates the models, blockstates and placeholder textures for the crossarms (issue #38).

Run from the repository root:

    python scripts/gen_crossarms.py

A crossarm is built from one-block segments that join into an arm of any length (BlockCrossarm).
Each segment's model depends on its neighbours: whether the arm carries on to its left and to its
right, and whether it sits against a pole, where a through-bolt holds it. The Java side relies on
the file names, and on the arm's cross-section matching BlockCrossarm.ARM_BOUNDS.

Coordinate system (as in gen_pole_light_mounts.py): one unit is one block, the segment's block spans
0..1, the segment faces NORTH (away from the pole) and the pole is the block to its SOUTH (z 1..2).
The arm runs along x. Left and right are seen looking out from the pole, so left is west (-x).
The blockstate rotates the models to the other facings.
"""

import json
import os

from gen_pole_light_mounts import Obj, png, write

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'main', 'resources', 'assets', 'realgrid')
MODEL_DIR = os.path.join(ROOT, 'models', 'block', 'crossarm')
BLOCKSTATE_DIR = os.path.join(ROOT, 'blockstates')
TEXTURE_DIR = os.path.join(ROOT, 'textures', 'blocks')

HEADER = '# Generated by scripts/gen_crossarms.py\n'
PX = 1 / 16
FACINGS = (('north', 0), ('east', 90), ('south', 180), ('west', 270))

ARM_LO = 10 * PX          # the arm's cross-section: 6 px square at the top back of the block
END_INSET = 0.5 * PX      # an open end stops just short of its block's edge

# name: (base colour, grain spread) of the placeholder wood texture
MATERIALS = {
    'brooks_brown': ((122, 84, 56), 10),
}


def arm_model(material, left, right, pole):
    obj = Obj('crossarm_%s_%s' % (material, key(left, right, pole)), 'crossarm.mtl', HEADER)
    obj.use(material)
    x0 = 0.0 if left else END_INSET
    x1 = 1.0 if right else 1.0 - END_INSET
    obj.box((x0, ARM_LO, ARM_LO), (x1, 1.0, 1.0))
    if pole:
        # Through-bolt: square washer and nut on the arm's front face.
        obj.use('steel')
        obj.box((6 * PX, 11 * PX, ARM_LO - 0.4 * PX), (10 * PX, 15 * PX, ARM_LO))
        obj.box((7 * PX, 12 * PX, ARM_LO - 1.0 * PX), (9 * PX, 14 * PX, ARM_LO - 0.4 * PX))
    return obj.text()


def key(left, right, pole):
    """'lrp'-style suffix: which of left, right and pole are set."""
    return ''.join(c for c, on in (('l', left), ('r', right), ('p', pole)) if on) or 'none'


def mtl():
    lines = [HEADER]
    for material in MATERIALS:
        lines.append('newmtl %s\nmap_Kd realgrid:blocks/crossarm_%s\n' % (material, material))
    lines.append('newmtl steel\nmap_Kd realgrid:blocks/pole_light_mount_clamp\n')
    return ''.join(lines)


def blockstate(material):
    def model(left, right, pole):
        return 'realgrid:crossarm/%s/arm_%s.obj' % (material, key(left, right, pole))
    variants = {}
    for facing, y in FACINGS:
        for left in (False, True):
            for pole in (False, True):
                for right in (False, True):
                    variants['facing=%s,left=%s,pole=%s,right=%s' % (
                        facing, str(left).lower(), str(pole).lower(), str(right).lower())] = {
                        'model': model(left, right, pole), 'custom': {'flip-v': True}, 'y': y}
    variants['inventory'] = {
        'model': 'realgrid:crossarm/%s/arm_%s.obj' % (material, key(True, True, True)),
        'custom': {'flip-v': True},
        'transform': {
            'gui': {'translation': [0, -0.1, 0], 'rotation': [{'x': 30}, {'y': 135}], 'scale': 0.6},
            'ground': {'translation': [0, 0.1, 0], 'scale': 0.4},
            'fixed': {'rotation': [{'y': 180}], 'scale': 0.6},
            'thirdperson': {'translation': [0, 0.1, 0.1], 'rotation': [{'x': 75}, {'y': 45}], 'scale': 0.45},
            'firstperson': {'translation': [0.1, 0.1, 0], 'rotation': [{'y': 45}], 'scale': 0.45},
        },
    }
    return {'forge_marker': 1, 'variants': variants}


def wood_texture(base, spread):
    """A placeholder: streaks of grain along the texture's rows, repeatable rather than random."""
    out = []
    for y in range(16):
        row = ((y * 7919) % 13) - 6
        for x in range(16):
            knot = -14 if (x * 31 + y * 17) % 97 == 0 else 0
            fleck = ((x * 2654435761 + y * 40503) >> 9) % 5 - 2
            shade = row * spread // 6 + fleck + knot
            out.append(tuple(max(0, min(255, c + shade)) for c in base))
    return out


def main():
    for material, (colour, spread) in MATERIALS.items():
        folder = os.path.join(MODEL_DIR, material)
        os.makedirs(folder, exist_ok=True)
        keep = set()
        for left in (False, True):
            for right in (False, True):
                for pole in (False, True):
                    name = 'arm_%s.obj' % key(left, right, pole)
                    keep.add(name)
                    write(os.path.join(folder, name), arm_model(material, left, right, pole))
        for stale in os.listdir(folder):
            if stale.endswith('.obj') and stale not in keep:
                os.remove(os.path.join(folder, stale))
        write(os.path.join(folder, 'crossarm.mtl'), mtl())
        write(os.path.join(BLOCKSTATE_DIR, 'crossarm_%s.json' % material), json.dumps(blockstate(material), indent=2) + '\n')
        png(os.path.join(TEXTURE_DIR, 'crossarm_%s.png' % material), wood_texture(colour, spread))


if __name__ == '__main__':
    main()
